lint:
  files_unchanged:
  - .gitignore
  - assets/nf-core-molkart_logo_light.png
  - docs/images/nf-core-molkart_logo_dark.png
  - docs/images/nf-core-molkart_logo_light.png
  files_exist:
  - conf/igenomes_ignored.config
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: "@kbestak, @FloWuenne"
  description: An analysis pipeline for Molecular Cartography data from Resolve Biosciences.
  force: false
  is_nfcore: true
  name: molkart
  org: nf-core
  outdir: .
  version: 1.2.0dev
